on:
    - push
    - pull_request
name: CI
jobs:
    win:
        name: Win
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - name: The test
              run: bash ./test.sh
